/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as AcademyBoostersRouteImport } from './routes/academy/boosters'
import { Route as AcademyDrillRouteImport } from './routes/academy/drill'
import { Route as AcademyErrorsRouteImport } from './routes/academy/errors'
import { Route as AcademyExamRouteImport } from './routes/academy/exam'
import { Route as AcademyFormulasRouteImport } from './routes/academy/formulas'
import { Route as AcademyMethodRouteImport } from './routes/academy/method'
import { Route as AcademyPapersRouteImport } from './routes/academy/papers'
import { Route as AcademyPracticeRouteImport } from './routes/academy/practice'
import { Route as AcademyStartRouteImport } from './routes/academy/start'
import { Route as AcademySyllabusRouteImport } from './routes/academy/syllabus'
import { Route as AcademyTracksRouteImport } from './routes/academy/tracks'
import { Route as AcademyBoostersIdRouteImport } from './routes/academy/boosters.$id'
import { Route as AcademyChapterIdRouteImport } from './routes/academy/chapter.$id'
import { Route as AcademyPapersIndexRouteImport } from './routes/academy/papers.index'
import { Route as AcademyPapersIdRouteImport } from './routes/academy/papers.$id'
import { Route as AcademyPracticeIdRouteImport } from './routes/academy/practice.$id'
import { Route as AcademySubjectSubjectRouteImport } from './routes/academy/subject.$subject'
import { Route as AcademyTracksIdRouteImport } from './routes/academy/tracks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyBoostersRoute = AcademyBoostersRouteImport.update({
  id: '/boosters',
  path: '/boosters',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyDrillRoute = AcademyDrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyErrorsRoute = AcademyErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyExamRoute = AcademyExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyFormulasRoute = AcademyFormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyMethodRoute = AcademyMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPapersRoute = AcademyPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPracticeRoute = AcademyPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyStartRoute = AcademyStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademySyllabusRoute = AcademySyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyTracksRoute = AcademyTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyBoostersIdRoute = AcademyBoostersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcademyBoostersRoute,
} as any)
const AcademyChapterIdRoute = AcademyChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPapersIndexRoute = AcademyPapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyPapersRoute,
} as any)
const AcademyPapersIdRoute = AcademyPapersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcademyPapersRoute,
} as any)
const AcademyPracticeIdRoute = AcademyPracticeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcademyPracticeRoute,
} as any)
const AcademySubjectSubjectRoute = AcademySubjectSubjectRouteImport.update({
  id: '/subject/$subject',
  path: '/subject/$subject',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyTracksIdRoute = AcademyTracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcademyTracksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/academy/boosters': typeof AcademyBoostersRouteWithChildren
  '/academy/drill': typeof AcademyDrillRoute
  '/academy/errors': typeof AcademyErrorsRoute
  '/academy/exam': typeof AcademyExamRoute
  '/academy/formulas': typeof AcademyFormulasRoute
  '/academy/method': typeof AcademyMethodRoute
  '/academy/papers': typeof AcademyPapersRouteWithChildren
  '/academy/practice': typeof AcademyPracticeRouteWithChildren
  '/academy/start': typeof AcademyStartRoute
  '/academy/syllabus': typeof AcademySyllabusRoute
  '/academy/tracks': typeof AcademyTracksRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/academy/boosters/$id': typeof AcademyBoostersIdRoute
  '/academy/chapter/$id': typeof AcademyChapterIdRoute
  '/academy/papers/$id': typeof AcademyPapersIdRoute
  '/academy/practice/$id': typeof AcademyPracticeIdRoute
  '/academy/subject/$subject': typeof AcademySubjectSubjectRoute
  '/academy/tracks/$id': typeof AcademyTracksIdRoute
  '/academy/papers/': typeof AcademyPapersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy/boosters': typeof AcademyBoostersRouteWithChildren
  '/academy/drill': typeof AcademyDrillRoute
  '/academy/errors': typeof AcademyErrorsRoute
  '/academy/exam': typeof AcademyExamRoute
  '/academy/formulas': typeof AcademyFormulasRoute
  '/academy/method': typeof AcademyMethodRoute
  '/academy/practice': typeof AcademyPracticeRouteWithChildren
  '/academy/start': typeof AcademyStartRoute
  '/academy/syllabus': typeof AcademySyllabusRoute
  '/academy/tracks': typeof AcademyTracksRouteWithChildren
  '/academy': typeof AcademyIndexRoute
  '/academy/boosters/$id': typeof AcademyBoostersIdRoute
  '/academy/chapter/$id': typeof AcademyChapterIdRoute
  '/academy/papers/$id': typeof AcademyPapersIdRoute
  '/academy/practice/$id': typeof AcademyPracticeIdRoute
  '/academy/subject/$subject': typeof AcademySubjectSubjectRoute
  '/academy/tracks/$id': typeof AcademyTracksIdRoute
  '/academy/papers': typeof AcademyPapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/academy/boosters': typeof AcademyBoostersRouteWithChildren
  '/academy/drill': typeof AcademyDrillRoute
  '/academy/errors': typeof AcademyErrorsRoute
  '/academy/exam': typeof AcademyExamRoute
  '/academy/formulas': typeof AcademyFormulasRoute
  '/academy/method': typeof AcademyMethodRoute
  '/academy/papers': typeof AcademyPapersRouteWithChildren
  '/academy/practice': typeof AcademyPracticeRouteWithChildren
  '/academy/start': typeof AcademyStartRoute
  '/academy/syllabus': typeof AcademySyllabusRoute
  '/academy/tracks': typeof AcademyTracksRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/academy/boosters/$id': typeof AcademyBoostersIdRoute
  '/academy/chapter/$id': typeof AcademyChapterIdRoute
  '/academy/papers/$id': typeof AcademyPapersIdRoute
  '/academy/practice/$id': typeof AcademyPracticeIdRoute
  '/academy/subject/$subject': typeof AcademySubjectSubjectRoute
  '/academy/tracks/$id': typeof AcademyTracksIdRoute
  '/academy/papers/': typeof AcademyPapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/academy/boosters'
    | '/academy/drill'
    | '/academy/errors'
    | '/academy/exam'
    | '/academy/formulas'
    | '/academy/method'
    | '/academy/papers'
    | '/academy/practice'
    | '/academy/start'
    | '/academy/syllabus'
    | '/academy/tracks'
    | '/academy/'
    | '/academy/boosters/$id'
    | '/academy/chapter/$id'
    | '/academy/papers/$id'
    | '/academy/practice/$id'
    | '/academy/subject/$subject'
    | '/academy/tracks/$id'
    | '/academy/papers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy/boosters'
    | '/academy/drill'
    | '/academy/errors'
    | '/academy/exam'
    | '/academy/formulas'
    | '/academy/method'
    | '/academy/practice'
    | '/academy/start'
    | '/academy/syllabus'
    | '/academy/tracks'
    | '/academy'
    | '/academy/boosters/$id'
    | '/academy/chapter/$id'
    | '/academy/papers/$id'
    | '/academy/practice/$id'
    | '/academy/subject/$subject'
    | '/academy/tracks/$id'
    | '/academy/papers'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/academy/boosters'
    | '/academy/drill'
    | '/academy/errors'
    | '/academy/exam'
    | '/academy/formulas'
    | '/academy/method'
    | '/academy/papers'
    | '/academy/practice'
    | '/academy/start'
    | '/academy/syllabus'
    | '/academy/tracks'
    | '/academy/'
    | '/academy/boosters/$id'
    | '/academy/chapter/$id'
    | '/academy/papers/$id'
    | '/academy/practice/$id'
    | '/academy/subject/$subject'
    | '/academy/tracks/$id'
    | '/academy/papers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/boosters': {
      id: '/academy/boosters'
      path: '/boosters'
      fullPath: '/academy/boosters'
      preLoaderRoute: typeof AcademyBoostersRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/drill': {
      id: '/academy/drill'
      path: '/drill'
      fullPath: '/academy/drill'
      preLoaderRoute: typeof AcademyDrillRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/errors': {
      id: '/academy/errors'
      path: '/errors'
      fullPath: '/academy/errors'
      preLoaderRoute: typeof AcademyErrorsRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/exam': {
      id: '/academy/exam'
      path: '/exam'
      fullPath: '/academy/exam'
      preLoaderRoute: typeof AcademyExamRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/formulas': {
      id: '/academy/formulas'
      path: '/formulas'
      fullPath: '/academy/formulas'
      preLoaderRoute: typeof AcademyFormulasRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/method': {
      id: '/academy/method'
      path: '/method'
      fullPath: '/academy/method'
      preLoaderRoute: typeof AcademyMethodRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/papers': {
      id: '/academy/papers'
      path: '/papers'
      fullPath: '/academy/papers'
      preLoaderRoute: typeof AcademyPapersRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/practice': {
      id: '/academy/practice'
      path: '/practice'
      fullPath: '/academy/practice'
      preLoaderRoute: typeof AcademyPracticeRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/start': {
      id: '/academy/start'
      path: '/start'
      fullPath: '/academy/start'
      preLoaderRoute: typeof AcademyStartRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/syllabus': {
      id: '/academy/syllabus'
      path: '/syllabus'
      fullPath: '/academy/syllabus'
      preLoaderRoute: typeof AcademySyllabusRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/tracks': {
      id: '/academy/tracks'
      path: '/tracks'
      fullPath: '/academy/tracks'
      preLoaderRoute: typeof AcademyTracksRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/boosters/$id': {
      id: '/academy/boosters/$id'
      path: '/$id'
      fullPath: '/academy/boosters/$id'
      preLoaderRoute: typeof AcademyBoostersIdRouteImport
      parentRoute: typeof AcademyBoostersRoute
    }
    '/academy/chapter/$id': {
      id: '/academy/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/academy/chapter/$id'
      preLoaderRoute: typeof AcademyChapterIdRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/papers/': {
      id: '/academy/papers/'
      path: '/'
      fullPath: '/academy/papers/'
      preLoaderRoute: typeof AcademyPapersIndexRouteImport
      parentRoute: typeof AcademyPapersRoute
    }
    '/academy/papers/$id': {
      id: '/academy/papers/$id'
      path: '/$id'
      fullPath: '/academy/papers/$id'
      preLoaderRoute: typeof AcademyPapersIdRouteImport
      parentRoute: typeof AcademyPapersRoute
    }
    '/academy/practice/$id': {
      id: '/academy/practice/$id'
      path: '/$id'
      fullPath: '/academy/practice/$id'
      preLoaderRoute: typeof AcademyPracticeIdRouteImport
      parentRoute: typeof AcademyPracticeRoute
    }
    '/academy/subject/$subject': {
      id: '/academy/subject/$subject'
      path: '/subject/$subject'
      fullPath: '/academy/subject/$subject'
      preLoaderRoute: typeof AcademySubjectSubjectRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/tracks/$id': {
      id: '/academy/tracks/$id'
      path: '/$id'
      fullPath: '/academy/tracks/$id'
      preLoaderRoute: typeof AcademyTracksIdRouteImport
      parentRoute: typeof AcademyTracksRoute
    }
  }
}

interface AcademyBoostersRouteChildren {
  AcademyBoostersIdRoute: typeof AcademyBoostersIdRoute
}

const AcademyBoostersRouteChildren: AcademyBoostersRouteChildren = {
  AcademyBoostersIdRoute: AcademyBoostersIdRoute,
}

const AcademyBoostersRouteWithChildren = AcademyBoostersRoute._addFileChildren(
  AcademyBoostersRouteChildren,
)

interface AcademyPapersRouteChildren {
  AcademyPapersIdRoute: typeof AcademyPapersIdRoute
  AcademyPapersIndexRoute: typeof AcademyPapersIndexRoute
}

const AcademyPapersRouteChildren: AcademyPapersRouteChildren = {
  AcademyPapersIdRoute: AcademyPapersIdRoute,
  AcademyPapersIndexRoute: AcademyPapersIndexRoute,
}

const AcademyPapersRouteWithChildren = AcademyPapersRoute._addFileChildren(
  AcademyPapersRouteChildren,
)

interface AcademyPracticeRouteChildren {
  AcademyPracticeIdRoute: typeof AcademyPracticeIdRoute
}

const AcademyPracticeRouteChildren: AcademyPracticeRouteChildren = {
  AcademyPracticeIdRoute: AcademyPracticeIdRoute,
}

const AcademyPracticeRouteWithChildren = AcademyPracticeRoute._addFileChildren(
  AcademyPracticeRouteChildren,
)

interface AcademyTracksRouteChildren {
  AcademyTracksIdRoute: typeof AcademyTracksIdRoute
}

const AcademyTracksRouteChildren: AcademyTracksRouteChildren = {
  AcademyTracksIdRoute: AcademyTracksIdRoute,
}

const AcademyTracksRouteWithChildren = AcademyTracksRoute._addFileChildren(
  AcademyTracksRouteChildren,
)

interface AcademyRouteChildren {
  AcademyBoostersRoute: typeof AcademyBoostersRouteWithChildren
  AcademyDrillRoute: typeof AcademyDrillRoute
  AcademyErrorsRoute: typeof AcademyErrorsRoute
  AcademyExamRoute: typeof AcademyExamRoute
  AcademyFormulasRoute: typeof AcademyFormulasRoute
  AcademyMethodRoute: typeof AcademyMethodRoute
  AcademyPapersRoute: typeof AcademyPapersRouteWithChildren
  AcademyPracticeRoute: typeof AcademyPracticeRouteWithChildren
  AcademyStartRoute: typeof AcademyStartRoute
  AcademySyllabusRoute: typeof AcademySyllabusRoute
  AcademyTracksRoute: typeof AcademyTracksRouteWithChildren
  AcademyIndexRoute: typeof AcademyIndexRoute
  AcademyChapterIdRoute: typeof AcademyChapterIdRoute
  AcademySubjectSubjectRoute: typeof AcademySubjectSubjectRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyBoostersRoute: AcademyBoostersRouteWithChildren,
  AcademyDrillRoute: AcademyDrillRoute,
  AcademyErrorsRoute: AcademyErrorsRoute,
  AcademyExamRoute: AcademyExamRoute,
  AcademyFormulasRoute: AcademyFormulasRoute,
  AcademyMethodRoute: AcademyMethodRoute,
  AcademyPapersRoute: AcademyPapersRouteWithChildren,
  AcademyPracticeRoute: AcademyPracticeRouteWithChildren,
  AcademyStartRoute: AcademyStartRoute,
  AcademySyllabusRoute: AcademySyllabusRoute,
  AcademyTracksRoute: AcademyTracksRouteWithChildren,
  AcademyIndexRoute: AcademyIndexRoute,
  AcademyChapterIdRoute: AcademyChapterIdRoute,
  AcademySubjectSubjectRoute: AcademySubjectSubjectRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
